### ISSUE TITLE
Inconsistency between DDL and data in Excel sheet for T_152 V08a (M) Entity Name Tag Defns

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#10]
The data sheet contains fields 

VIEW_DATA_SCRIPT_GROUP_KEY | VIEW_DATA_SCRIPT_PID | MODIFY_DATA_SCRIPT_GROUP_KEY | MODIFY_DATA_SCRIPT_PID | DELETE_DATA_SCRIPT_GROUP_KEY | DELETE_DATA_SCRIPT_PID

which are empty, but which are there. This means that an export from Excel into a csv and a load into the H2 database fails with "Unexpected number of values. Data loading failed."

Is this intentional?

**Comment by MichaelErichsen** [comment]
Correction: The missing field is 
RECORD_NUM INTEGER   NOT NULL,
which prevent a direct unload/load

**Comment by HREferg** [comment]
Hi - we're a bit confused on this one. The field RECORD_NUM INTEGER NOT NULL
does exist in T_152; and is included in both locations required in the DDL (Rod thinks).
Yes, data is missing in the Spreadsheet from the DATA_TYPE_KEY column in the FIELDS (T_107) sheet, and in most cases from the DATA/USER sheet and TRANS (T_204) sheets, but that doesn't affect the DDL.
Can you give us more direction?

**Comment by MichaelErichsen** [comment]
Hi

Sorry for not being clear. The issue is in the load of data.

From Excel you can export the data from the sheet to a csv file.
You can import a csv file into h2, if the csv file holds the same
columns as the table, but not when columns are missing.
This is important when we have hundreds of tables to load.

Mvh Michael Erichsen

**Comment by MichaelErichsen** [comment]
Sorry for not being clear. The issue is in the load of data.

From Excel you can export the data from the sheet to a csv file.
You can import a csv file into h2, if the csv file holds the same columns as the table, but not when columns are missing.
This is important when we have hundreds of tables to load.

**Comment by HREferg** [comment]
Ah! Then yes, you will have problems, as the Excel files are not yet ready for preloading purposes (Rod to confirm).

 

Don

**Comment by MichaelErichsen** [comment]
Sorry for a **very** late answer. What I had expected was data that could be exported as csv from the Excel sheet and then imported directly into H2, which would save a lot of work. And for that purpose the Excel sheet columns need to match the columns in the DDL excatly.

Br Michael
