### ISSUE TITLE
Icon sizes

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#17]
Hi Don

Would it be possible to have the icons as 32*32, which is the best size for the Eclipse toolbar?

Br Michael

**Comment by HREferg** [comment]
Good question! I'm guessing we'll need a whole bunch of sizes. Will ask Rod, whose been doing the icons.

Don

**Comment by HREferg** [comment]
Loaded up 32x32 and 48x48 versions.
Don
