### ISSUE TITLE
Add Help System

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#22]

**Comment by MichaelErichsen** [comment]
If you provide a set of Word documents you would like to have in the first cut of the help system, pls. let me know.
You can take a look at the help system in the Mock up to see how Word documents have been generated into the Eclipse Help system semi-automatically.

**Comment by RodThompson** [comment]
To my knowledge (and I am the newbie to this Project) there is no definition for the Help system at this time.  I see the value of having the system within HRE as well as the Wiki.  But they should be different.  All effort here is presently directed towards getting design documentation to a stage where code development can proceed without interruption.  My estimate would be several months before initial help system documentation could be started.
I can see the value of having a few simple paragraphs added initially as a test exercise.
Need to think about that structure.

**Comment by moshedavis** [comment]
Hi all,
In terms of setting up a help system:

I read the document 05.14 GUI_Help. There are a number of Help Authoring Tools (HATs) which will semi-automatically produce a complete help system as described. There is no need to develop the Help interface from scratch.

There are two aspects to building such a help system from a HAT: (1) authoring the material in the source topics (2) configuring the needed output. 

Examples of delivered output might be, for example: a complete HTML help site, or context-sensitive help integrated into the HRE GUI, or printed documentation such as PDF. The various types of deliverable output can all be produced from a single set of source topics. Content can be marked conditionally to be included/excluded from various outputs. 

From the HRE developers' perspective, all that should be needed is to integrate the resulting help system into the HRE interface.

I'm not sure what you are doing with a "set of Word documents". If needed, I can provide a sample output from a HAT for the developers to work with.

Hope this helps,
Moshe

**Comment by MichaelErichsen** [comment]
Hi Moshe

Thank you

When we built a mock up this winter we used a tool chain converting Word docx to Libre Office odt to docbook to Eclipse help system. This was combined from a couple of cookbooks and only took a few edits and a couple of XML translate scripts. And it worked fine. So I think we are fine so far.

**Comment by MichaelErichsen** [comment]
If you are interested, you can find the tool chain in [https://github.com/MichaelErichsen/HRE_Helpsystem_Generator.git](https://github.com/MichaelErichsen/HRE_Helpsystem_Generator.git)

**Comment by moshedavis** [comment]
Yes, I'll give your documentation tool chain a look. I've begun researching the Eclipse Help system.

**Comment by moshedavis** [comment]
Having quickly looked at the documentation tool chain and begun initial research into the Eclipse Help system, I will venture a few comments/ suggestions:

Authoring an Eclipse Help system seems to require two main steps: (a) authoring content (b) creating from that content an Eclipse plugin. 

The described documentation tool chain:
(a) uses MSWord/Libre Office for authoring. 
(b) The Eclipse Help system is created by translation to Docbooks (XML) format, followed by using an Ant build to create an Eclipse Help system from the Docbooks format.

Comments:

(a) Authoring content:

- Authoring content is in essence independent of the Eclipse IDE. Theoretically, any editor can be used to author the help content.
- I strongly feel that the content should be based on a topic-based architecture (see below). 
- Topic-based architecture allows for efficient content reuse, single sourcing for multiple types of output, and ease of translation.
- Each topic should be a unit of information about a single subject, which makes sense by itself, and is not dependent on being part of a larger document.
- Individual topics should be modular and consistently structured.
- A structured approach is necessary to efficiently organize and assemble such independently authored topics from a common pool of topics to produce different deliverable documents, such as a help system, a wiki, or PDF.

Formats such as MSWord or Docbooks are oriented more for linear (as opposed to topic-based) authoring. There are many XML editors and Help Authoring Tools (HATs) which were designed specifically for topic-based authoring. 

(b) Creating an Eclipse Help plugin:

Many XML editors and Help Authoring Tools (HATs), in addition to providing a mature environment for both authoring and organizing content, also can produce a complete Eclipse Help plugin as deliverable output. I would highly recommend going that path. Many XML editors and HATs are themselves proprietary tools, but even of those, most use open-source technology and produce standard non-proprietary output.

All of the above are open to discussion.
Hope this helps,
Moshe

**Comment by moshedavis** [comment]
p.s. I am receiving emails of Michael's comments, but not of my own. Is that normal for the GitHub issue system?

**Comment by richard-damon** [comment]
I don't know for certain, but many notification systems won't notify you of your own actions. After all, you should know that you made a comment to that thread. They assume that the comment system will be the 'master', and not that you want a complete copy of the issue in your inbox.

**Comment by moshedavis** [comment]
It is a Github account setting:
Personal settings > Notifications > Email notification preferences > Include your own updates
(disabled by default)

**Comment by MichaelErichsen** [comment]
Help system has now been added, but some problems to display the right pages.

**Comment by MichaelErichsen** [comment]
Help systrem now displays the old Mockup help
