### ISSUE TITLE
GUI_ProjectOpen – Open a Project

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#27]
The normal Eclipse way to do this is to have a table part with the projects, where the user can select actions on a selected project or for something that is not yet there.
Please see my implementation in the skeleton.

Br Michael

**Comment by MichaelErichsen** [comment]
I have implemented two different functions: Open selected and Open other.
The projects menu item opens a table of known (or registered projects). They are physically stored in the Eclipse preferences file, managed by the platform.
If you select one and right click Open selected, it is opened.
If you right click Select other anywhere in the view part, I first open the standard file open dialog to select and .h2.db or .mv.db file. I then display a dialog box to add Project Name and summary. I pick the last-modified timestamp from the file system, and I add the project to the properties file and the view part.
"Open" is really not yet clearly defined, so I open the technical table navigator from the database adminstration tool to at least prove I got it right. Later it should be a more meaningful display from a user perspective.

**Comment by RodThompson** [comment]
You may be interested to know that I can now run your mockup on my main computer.
An upgrade to hardware revealed a Windows corruptions (not otherwise detected)

Running the mockup, I can see what you have done in this area.
Please explain your comment – “Open” is really not yet clearly defined.
Clarifications are essential so all know the relevant meanings of everything written.
Easier said than done.

**Comment by MichaelErichsen** [comment]
Hi Rod

Please don't close an issue in the middle of a conversation. It then disappears from plain sight.

When I open a project in TMG, it opens what would be a perspective in Eclipse terms: A defined (and user configurable) set of view parts, which collectively is the main workbench for genealogy work.
No such parts have yet been defined by the HRE project, so I am just opening the technical database administration navigator, while building the skeleton "bottom-up".

**Comment by HREferg** [comment]
Closed - no longer relevant to current build of HRE.
