### ISSUE TITLE
GUI_ProjectNew – Create a New Project

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#28]
This has been replaced by a standard dialog with an added dialog box for project name and Summary in the skeleton.

**Comment by MichaelErichsen** [comment]
The function at this popint in time creates all tables, but loads nothing. It also creates an entry in the Eclipse properties file.

**Comment by RodThompson** [comment]
The present action of the module is understandable, given that the database is not yet usable.
What is the Eclipse properties file all about?

**Comment by MichaelErichsen** [comment]
Reopening the issue to answer.

Eclipse is the platform, we are building HRE upon.
Eclipse is in my view a very good choice, when the programming language is Java (which I also am happy about), because it provides a large number of services to relieve the programming effort.
Every Eclipse application is born with a set of properti

**Comment by HREferg** [comment]
Closed - no longer relevant to current Build of HRE
