### ISSUE TITLE
Help About

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#30]
Update Help About to the description in 04.15 GUI_Help_AboutHRE 2018-05-31.pdf

**Comment by MichaelErichsen** [comment]
Hi

I find it rather counterproductive that you have a long text in this document, but has made it non-machinereadable, so I have to type it in again from a picture.

**Comment by MichaelNMaggs** [comment]
I would suggest that as a matter of principle we should *never* be uploading text in image format. 

Michael

**Comment by RobinLamacraft** [comment]
Hi Michael,

One issue that I had note thought about. I hope that this request below 
will avoid it in the future.

Don, Rod > For the future, please make sure any special text that is in 
an image in the GUI documents is also included as a normal text string 
with the the appropriate document.

Robin


On 16-Jun-18 03:45 AM, Michael Erichsen wrote:
> but has made it non-machinereadable

-- 
Robin Lamacraft, Adelaide, Australia


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by HREferg** [comment]
You have a point!  I’ll add the text to the raw documentation too.

 

The text you’re after (I presume) is the stuff in the splash screen, which looks like:

 

“History Research Environment (HRE) is a community project to create a free open source platform for recording a wide range of genealogical, historical and social research.

The development community is supported by a not-for-profit company, History Research Environment Limited, limited by guarantee and registered under the laws of England and Wales.

All code developed by HRE is copyright the individual developers, and is released under the GNU Affero General Public Licence (GNU AGPL) https://www.gnu.org/licenses/agpl-3.0.en.html.  For further details, see http://hrewiki.org/index.php?title=Why_have_we_chosen_these_licences%3F.  

Reuse of the HRE software is permitted only under the terms of the licence. Using the HRE software or any derivative of the software to offer a service over the internet is strictly prohibited.

Website: https://historyresearchenvironment.org/
Wiki: http://hrewiki.org “

 

Don

**Comment by MichaelErichsen** [comment]
Have finished the About dialog by hand in the meantime. Just wanted to improve the process for the future.
