### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#32]
Hi

Eclipse prefers icons in the PNG format at 32*32 pixels.

Br Michael

**Comment by HREferg** [comment]
Yes, it would, wouldn't it?
I've reloaded the HRE logo that was jpg as png, but its not meant to be an icon, just a graphic for use in places like splash screens etc. Wouldn't fit as an icon as it isn't square. Changed it's name as well to make it clear its not an icon.
Don
