### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#34]
The log displays the following:

Root exception:
java.nio.file.NoSuchFileException: c:\temp\hre-log.0.0.txt.lck

This is due to that HRE by default tries to create a log file in the directory c:\temp

**Comment by MichaelErichsen** [comment]
The solution will be to change this to the installation directory.

**Comment by MichaelErichsen** [comment]
A workararound is to create a directory called c:/temp until the fix is ready.

**Comment by HREferg** [comment]
Aha! The old C:/temp/ issue – confirm that creating a C:/temp folder fixes things – a whole lot of different things now evident.

 

Don

**Comment by HREferg** [comment]
Believe it would be better to set the log file into c:/Users/username/HRE/….  And whatever the equivalent is in the Mac and Linux worlds.

 

Don

**Comment by richard-damon** [comment]
You probably want to use the environment variables to get the base home directory path
$USERPROFILE on Windows and $HOME on *nix including OS/X

It might have been moved to someplace else when they configured the system.

**Comment by MichaelErichsen** [comment]
@HREferg: This is indeed a known error. I have built v0.1 from the ground up, while migrating features from the mock up. Along the way some things have been hardcoded, which now surface, as you are starting to test. 
@richard-damon: We don't need to fiddle with more environment variables than JAVA_HOME. There are **two** standard locations that will always work:

- One is "." (dot), which is the installation directory of HRE, from which we run eclipse.exe. 

- The other is "~" (tilde), which is shorthand for the home directory on all platforms. I.e. /users/michael on my Windows system and /u/michael or /home/michael on Unix systems. 

Both will always work. The lazy programmer just needs to avoid hardcoding other locations.
HRE already has a preferences setting for the log location, which users can modify in the preferences panels. I need to put the initial default in one of these as noted above.

**Comment by MichaelErichsen** [comment]
org.historyresearchenvironment.client.HreLogger changed from
		String logFilePath = preferences.get("LOGFILEPATH", "c:\\temp\\");
to
		String logFilePath = preferences.get("LOGFILEPATH", ".");

**Comment by MichaelErichsen** [comment]
This has now been fixed in build 0.1.0.201806241508, which adds a sample database in the execution root and points to it and also by default puts the log there.
