### ISSUE TITLE
Display Build Date to the user

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#35]
This could make error reporting and debugging easier.

Suggestions on how to do it in
https://rterp.wordpress.com/2012/03/16/stamping-version-number-and-build-time-in-properties-file-with-maven/

**Comment by ricko2001** [comment]
Build timestamp is fine, but please also :
tag the git repo with the build number/timestamp
and
include the git commit sha in the build a well.

I think it is critical that each build used for testing by anyone except
the developer be done from a completely defined set of files and procedures
saved in the git repo. (sorry if this is obvious)

**Comment by MichaelErichsen** [comment]
Hi

This is definitely not obvious to me. I would be grateful to be advised on how best to do this.

**Comment by ricko2001** [comment]
It's all part of setting up a build system.
Perhaps it's too early to worry about now, but I think it should be in
place by the time non-developers start testing.
The goal is to create a repeatable build process without manual steps so
that there is an absolute link between the final build product and the
source code and tools used to create it.

Write a "Build Script" in a  scripting language that will-
- automate the retrieval of files from GitHub into an empty folder
- obtain the sha value of the current git commit
- create a timestamp value that will be used as a build number
- save the sha value and timestamp in such a way that they are available to
the build tool
- run the "compiler" (or whatever it's called in Java)

The app's about box could then display the sha value and timestamp.

 For C++ builds, the build script updates a .h file so the app has access
to the variable defined at build time (like the time stamp and git sha).
For C# builds, the build script updates custom attributes in the
AssemblyIno.cs file.

on another matter-
Any idea how you will be affected by the recent Java licensing roadmap put
out  by Oracle?

**Comment by HREferg** [comment]
Certainly a (single) build version no. of HRE placed somewhere easily found will make a lot of sense for test/debug work.

 

Don

**Comment by HREferg** [comment]
Closed - performed in Help About screen in current Build of HRE
