### ISSUE TITLE
Add editing to the Project Properties view part

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#36]
A right-click should open the ProjectNameSummaryDialog for updating.
Also clear table before inserting properties.

**Comment by HREferg** [comment]
I’m about to document a ‘Project Admin’ module – its needed to be able to adjust /edit values in the non-database files.

 

Don

**Comment by HREferg** [comment]
Closed - no longer relevant to current Build of HRE
