### ISSUE TITLE
Jython Support

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#42]
_From @MichaelErichsen on October 23, 2017 10:46_

I would also be very interested within the Eclipse environment to be able to use Jython as a scripting language for report composition. 

I would like to see this as a way where report scripts can be modified by more expert users to achieve bespoke reports. 

Hence the concept would be that Jython would access the HRE Java components to sequence a report. 

I understand that Jython scripts can also contain their own options selection GUI via Swing components initiated from the Jython script. 

I don't want HRE to be limited to the rigid canned reports that we have in TMG.

(Robin)

_Copied from original issue: MichaelErichsen/HRE--History-Research-Environment#31_

**Comment by MichaelErichsen** [comment]
Jython is an implementation of the high-level, dynamic, object-oriented language Python seamlessly integrated with the Java platform. The predecessor to Jython, JPython, is certified as 100% Pure Java. Jython is freely available for both commercial and non-commercial use and is distributed with source code. Jython is complementary to Java and is especially suited for the following tasks:

    Embedded scripting - Java programmers can add the Jython libraries to their system to allow end users to write simple or complicated scripts that add functionality to the application.
    Interactive experimentation - Jython provides an interactive interpreter that can be used to interact with Java packages or with running Java applications. This allows programmers to experiment and debug any Java system using Jython.
    Rapid application development - Python programs are typically 2-10X shorter than the equivalent Java program. This translates directly to increased programmer productivity. The seamless interaction between Python and Java allows developers to freely mix the two languages both during development and in shipping products.

**Comment by MichaelErichsen** [comment]
How to Connect Python to H2:
https://stackoverflow.com/questions/41493117/connect-python-to-h2

**Comment by MichaelErichsen** [comment]
It is possible that this can be used:
http://www.pydev.org/index.html

**Comment by MichaelErichsen** [comment]
Also
https://stackoverflow.com/questions/33868279/use-jython-in-eclipse-plugin

**Comment by MichaelErichsen** [comment]
And https://stackoverflow.com/questions/30099299/eclipse-rcp-and-jython

**Comment by MichaelErichsen** [comment]
Installed Pydev plugin from Eclipse Marketplace

**Comment by MichaelErichsen** [comment]
Added jython.jar from the Jython installation directory to the "Other jars" directory, which is part of the Plug-in Target Platform

**Comment by MichaelErichsen** [comment]
Added an access rule for org/python/** in Java Build Path, Libraries, Plug-in Dependencies

**Comment by MichaelErichsen** [comment]
Created a Java Plug-in project for testing.
PyDev, Set as PyDev project.
Configured Jython in the project properties.
Added both Java code and Jythin code in the src folder of the project

**Comment by MichaelErichsen** [comment]
# A python module that implements a Java interface to
# create a building object
from org.jython.book.interfaces import BuildingType

class Building(BuildingType):
    def __init__(self, name, address, id):
        self.name = name
        self.address = address
        self.id = id

    def getBuildingName(self):
        return self.name

    def getBuildingAddress(self):
        return self.address

    def getBuldingId(self):
        return self.id

**Comment by MichaelErichsen** [comment]
/**
 *
 * Object Factory that is used to coerce python module into a
 * Java class
 */
package org.jython.book.util;

import org.jython.book.interfaces.BuildingType;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.util.PythonInterpreter;

public class BuildingFactory {

    private PyObject buildingClass;

    /**
     * Create a new PythonInterpreter object, then use it to
     * execute some python code. In this case, we want to
     * import the python module that we will coerce.
     *
     * Once the module is imported than we obtain a reference to
     * it and assign the reference to a Java variable
     */

    public BuildingFactory() {
        PythonInterpreter interpreter = new PythonInterpreter();
        interpreter.exec("from Building import Building");
        buildingClass = interpreter.get("Building");
    }

    /**
     * The create method is responsible for performing the actual
     * coercion of the referenced python module into Java bytecode
     */

    public BuildingType create (String name, String location, String id) {

        PyObject buildingObject = buildingClass.__call__(new PyString(name),
                                                         new PyString(location),
                                                         new PyString(id));
        return (BuildingType)buildingObject.__tojava__(BuildingType.class);
    }

}

**Comment by MichaelErichsen** [comment]
// Java interface for a building object
package org.jython.book.interfaces;

public interface BuildingType {

    public String getBuildingName();
    public String getBuildingAddress();
    public String getBuildingId();

}

**Comment by MichaelErichsen** [comment]
SWT from Jython: https://stackoverflow.com/questions/516571/is-it-possible-to-use-swt-from-jython

**Comment by LynnAnnMcL** [comment]
What does that mean?
thanks, Lynn
