### ISSUE TITLE
Build: Force Maven/Tycho to use the current version of H2

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#56]
Maven Tycho fetches H2 from an Internet site at version 1.3.168, even though HRE has been built with a higher versions.

Find out how to force it.

**Comment by MichaelErichsen** [comment]
Run mvn dependency:tree -Dverbose -Dincludes=h2

Get
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.historyresearchenvironment.client 0.1.0.qualifier
[ERROR]   Missing requirement: org.historyresearchenvironment.dataaccess 0.1.0.qualifier requires 'bundle org.h2 1.4.197' but it could not be found
[ERROR]   Cannot satisfy dependency: org.historyresearchenvironment.client 0.1.0.qualifier depends on: bundle org.historyresearchenvironment.dataaccess 0.0.0
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.

**Comment by MichaelErichsen** [comment]
Added 1.4.196 to "Other jars".
Stipulated the version in the plug-in manifest.
Stipulated the version in the Target Platform

**Comment by MichaelErichsen** [comment]
H2 197 is dependent on org.apache.lucene 3.6.2, which can be fetched from http://archive.apache.org/dist/lucene/java/3.6.2/

**Comment by MichaelErichsen** [comment]
Found no solution.

**Comment by HREferg** [comment]
Michael – does this mean we can use h2 197 if we also install this lucene addin, or is the Maven over-write still an issue?

Don

**Comment by MichaelErichsen** [comment]
No. Sorry.

Still can't make it work as I want.

Mvh Michael Erichsen

**Comment by MichaelErichsen** [comment]
First changed to code to test for the version and insert row count zero in the DBADMIN navigator, when the version was lower than 1.4.
Then found out that the call to test the version also only is available at 1.4.
So tested for whether the test could run at all.
Sp the code is fixed, but I still am building with the old version.

**Comment by MichaelErichsen** [comment]
Changed settings.xml in the Maven installation to point to http.//repo2.maven.org/maven2
Then in Eclipse:
Preferences
Maven
User Settings
Global settings
Was blank, but should point to C:\Program Files\apache-maven-3.5.0\conf\settings.xml

But still no effect

**Comment by HREferg** [comment]
Closed - no longer relevant to current Build of HRE
