### ISSUE TITLE
REPORTING: Which output formats to support?

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#66]
LaTEX?
ODT?
CSV?
HTML?

Can we use XSLT for formatting between formats?

**Comment by HREferg** [comment]
This is briefly discussed at a high-level in module 07.01.

However, output is not expected to be dwelt on in detail until a much later (v0.7?) version of HRE. The thinking has been to extend Jython scripting definition to LaTeX creation, then LaTeX conversion to other output formats.

 

Don

**Comment by HREferg** [comment]
Closed - no longer relevant to current Build of HRE
