### ISSUE TITLE
DATABASE: Remove 1.3.168 Requirement in code and cookbook

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#68]
Check version of H2 and insert logic to circumvent lower versions than 1.4.
In practice that means that the Row Count column in the database navigator in the DBADMIN perspective will be meaningful in 1.4, but always set to 0 in 1.3.

**Comment by MichaelErichsen** [comment]
This has been implemented and will be part of the next build.
@Don: The requirement in the Cookbook can be removed.

**Comment by HREferg** [comment]
Cookbook updated as of Aug 5 edition.
