### ISSUE TITLE
DDL Defects

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#9]
Three tables are without primary keys:
CITN_TYPE_DEFNS
SUBSET_PAIR_DEFNS
SUBSET_SINGLE_DEFNS
Is that intentional or a defect?

**Comment by HREferg** [comment]
Fixed in DDL v8d reloaded 2018-04-02 (I think)

**Comment by HREferg** [comment]
Now corrected in DDL v8e 2018-04-05
